function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("hit3") then
		sprite.play_flipbook("#sprite", "explosion", function()
		sprite.play_flipbook("#sprite", "boule")
		end)

	end
end
function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
